INSERT INTO `vecnamoda`.`category` (`name`) VALUES ('women');
INSERT INTO `vecnamoda`.`category` (`name`) VALUES ('men');
INSERT INTO `vecnamoda`.`category` (`name`) VALUES ('children');
INSERT INTO `vecnamoda`.`category` (`name`, `parent_category_id`) VALUES ('w_top', '1');
INSERT INTO `vecnamoda`.`category` (`name`, `parent_category_id`) VALUES ('w_bottom', '1');
INSERT INTO `vecnamoda`.`category` (`name`, `parent_category_id`) VALUES ('w_accessory', '1');
INSERT INTO `vecnamoda`.`category` (`name`, `parent_category_id`) VALUES ('w_shirt', '4');
INSERT INTO `vecnamoda`.`category` (`name`, `parent_category_id`) VALUES ('w_jacket', '4');
INSERT INTO `vecnamoda`.`category` (`name`, `parent_category_id`) VALUES ('w_pants', '5');
INSERT INTO `vecnamoda`.`category` (`name`, `parent_category_id`) VALUES ('w_skirt', '5');
INSERT INTO `vecnamoda`.`category` (`name`, `parent_category_id`) VALUES ('w_shorts', '5');
INSERT INTO `vecnamoda`.`category` (`name`, `parent_category_id`) VALUES ('w_dress', '1');
INSERT INTO `vecnamoda`.`category` (`name`, `parent_category_id`) VALUES ('m_top', '2');
INSERT INTO `vecnamoda`.`category` (`name`, `parent_category_id`) VALUES ('m_bottom', '2');
INSERT INTO `vecnamoda`.`category` (`name`, `parent_category_id`) VALUES ('m_shirt', '13');
INSERT INTO `vecnamoda`.`category` (`name`, `parent_category_id`) VALUES ('m_jacket', '13');
INSERT INTO `vecnamoda`.`category` (`name`, `parent_category_id`) VALUES ('m_pants', '14');
INSERT INTO `vecnamoda`.`category` (`name`, `parent_category_id`) VALUES ('m_shorts', '14');
INSERT INTO `vecnamoda`.`category` (`name`, `parent_category_id`) VALUES ('c_top', '3');
INSERT INTO `vecnamoda`.`category` (`name`, `parent_category_id`) VALUES ('c_bottom', '3');
INSERT INTO `vecnamoda`.`category` (`name`, `parent_category_id`) VALUES ('c_dress', '3');
INSERT INTO `vecnamoda`.`category` (`name`, `parent_category_id`) VALUES ('c_shirt', '19');
INSERT INTO `vecnamoda`.`category` (`name`, `parent_category_id`) VALUES ('c_pants', '20');
INSERT INTO `vecnamoda`.`category` (`name`, `parent_category_id`) VALUES ('c_skirt', '20');
